#main.yml

---

- hosts: all
  tasks:

  - name: update cache
    apt:
      update_cache: yes

  - name: Install Apache2    
    apt:
      name: apache2
      state: present

  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos

  - name: Display hostname
    shell: echo "<h1>Hi Guys, building this project almost took my life but I didnt die, See you at the finish line.<br/> I'm Zainab btw, nice to meet whoever is checking this out 
     !! This is $(hostname -f) and the date is $(date)</h1>" > /var/www/html/index.html
    notify: restart_apache

  handlers:
  - name: restart_apache
    systemd:
      name: apache2
      state: restarted